nics: # number of nics needs to equal to 2
  - name: "eth2" # name of the interface
    subnet: "10.3.0.0/16" # IPv4 subnet in CIDR notation
    subnet_v6: "fdda:dead:beef:dab3::1:1/64" # IPv6 subnet in CIDR notation
    gateway: "10.3.1.1" # default IPv4 gateway
    gateway_v6: "fdda:dead:beef:dab3::1:1" # default IPv6 gateway
    last_bytes_v6: 0xcccccc # last bytes of the random ip addresses used ; Needs to match at least the last 3 bytes of an IPv6 address assigned to this interface (only if promiscuous mode is not enabled, otherwise this can be whatever)
  - name: "eth3"
    subnet: "10.3.0.0/16"
    subnet_v6: "fdda:dead:beef:dab3::1:1/64"
    gateway: "10.3.1.1"
    gateway_v6: "fdda:dead:beef:dab3::1:1"
    last_bytes_v6: 0xaaaaaa
